### ISSUE TITLE
[CY-2526] E2E tests of clang tidy should run the original tool

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-clang-tidy#18]
Current E2E tests on Clang tidy assume a correct tool's output.
It should run the real clang-tidy on some C++ files, pipe the result to codacy-clang-tidy and then send it to codacy as it already does.
Moreover it should have a negative test too.

## TODOs

- [ ] Run real clang-tidy in integration test
- [ ] Have a negative test

**Comment by heatherleeann** [comment]
> Current E2E tests on Clang tidy assume a correct tool's output. It should run the real clang-tidy on some C++ files, pipe the result to codacy-clang-tidy and then send it to codacy as it already does. Moreover it should have a negative test too.
> ## TODOs
> 
>     * [ ]  Run real clang-tidy in integration test
> 
>     * [ ]  Have a negative test
