### ISSUE TITLE
[CY-5053] exec format error to codacy-clang-tidy installable on Mac

### ISSUE THREAD

**Issue by pm-preety-narvekar** [codacy/codacy-clang-tidy#33]
**Environment** | **Version/Ids**
------------- | -----------
MacOS | Big Sur 11.2.2
Docker Desktop | 4.0.1
Docker Desktop engine | 20.10.8
codacy-clang-tidy release | 1.2.5
codacy-clang-tidy master commit | 7f6cebda08d87784e75773c8da8e89de14c59ae2

Hello team,

We need to analyze Objective-C source code using codacy, so are using codacy-clang-tidy tool as guided by codacy team.
When I tried to send results to codacy as mentioned [here](https://github.com/codacy/codacy-clang-tidy), I got following error:

```
preety% ./codacy-clang-tidy-1.2.5 
zsh: exec format error: ./codacy-clang-tidy-1.2.5
```
Looks like the installable is build for linux machine.
```
preety% file codacy-clang-tidy-1.2.5 
codacy-clang-tidy-1.2.5: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=a178261362452b3f44866076178dcfcbb8aec801, with debug_info, not stripped
```

Then, I tried to build a native binary as per the setps given in [Building](https://github.com/codacy/codacy-clang-tidy) section, used this new binary, followed the same steps to run the tool and send the report to codacy, but I still got the same error:
```
preety% ./codacy-clang-tidy-1.2.5        
zsh: exec format error: ./codacy-clang-tidy-1.2.5
```
The native image created by the steps is POSIX tar.
```
preety% file codacy-clang-tidy-1.2.5 
codacy-clang-tidy-1.2.5: POSIX tar archive
```

Could you please help me to understand how to proceed with this?

Thanks in advance!!

**Comment by lolgab** [comment]
Hi @pm-preety-narvekar,
Thank you for opening this issue.
The `codacy-clang-tidy` binary was a linux binary, also the "Building" section of the documentation was not updated to use the command we use nowadays (`sbt nativeImage`).
In #34 I made the CI publish a darwin binary together with the linux binary, so you can download the 1.3.1 darwin binary without having to build it yourself.

**Comment by pm-preety-narvekar** [comment]
Great!! Thanks for fixing it so quickly!!
